### ISSUE TITLE
Spell check cannot be enabled

### ISSUE THREAD

**Issue by mbarbar** [otherjoel/vim-pollen#1]
Thanks for this. Works great.

Is there any way to enable Vim's spell checker (`:set spell`) for normal/string text? The first screenshot is when filetype is `pollen`, and the second is when it is not.

![pollen_000](https://user-images.githubusercontent.com/12083002/72491684-ddfb1880-386e-11ea-8bbf-d3f87fccec66.png)
![not-pollen](https://user-images.githubusercontent.com/12083002/72491694-e4899000-386e-11ea-9758-9ffb2e5fa7c5.png)

**Comment by otherjoel** [comment]
Can you try editing line 102 of `syntax/pollen.vim` to add `,@Spell` to the end of the `contains` clause as shown below?

```vim
syntax region polBraceRange  matchgroup=Delimiter start="{" end="}" contains=polExprStart,polComment,polMultilineComment,@Spell contained
```

I tried this and it seems to work, but I have never used Vim's spell checker so I don’t know if it behaves in the way you expect.

**Comment by otherjoel** [comment]
I figured it out. Thanks for the report!

**Comment by mbarbar** [comment]
Works perfectly! Thanks for taking a look into it.
